{{- if and (not .Values.auth.existingSecret) (not .Values.externalSecrets.enabled) }}
{{- $encKeyName := .Values.auth.secretKeys.encryptionKey -}}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace (include "codex-lb.fullname" .)) -}}
{{- $existingEncKey := "" -}}
{{- if $existingSecret -}}
  {{- $existingEncKey = (index $existingSecret.data $encKeyName | default "") -}}
{{- end -}}
{{- $encKey := "" -}}
{{- if .Values.auth.encryptionKey -}}
  {{- $encKey = .Values.auth.encryptionKey -}}
{{- else if .Values.encryptionKey -}}
  {{- $encKey = .Values.encryptionKey -}}
{{- else if $existingEncKey -}}
  {{- $encKey = ($existingEncKey | b64dec) -}}
{{- else -}}
  {{- $encKey = randBytes 32 -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codex-lb.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "codex-lb.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- if not .Values.externalDatabase.existingSecret }}
  {{ .Values.auth.secretKeys.databaseUrl }}: {{ include "codex-lb.databaseUrl" . | quote }}
  {{- end }}
  {{ .Values.auth.secretKeys.encryptionKey }}: {{ $encKey | quote }}
{{- end }}
